### ISSUE TITLE
Screen Resolution on Windows can cause some fields are not displayed on browser in USS Explorer

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/explorer-uss#30]
With Zowe build 414:

The `New File/Directory Name` field in popup dialog is not displayed if the Windows Screen Resolution (height) is lower than 846, for example 1280×800. (Browser Zoom=100%) This will affect:

- Save File As ("New File Name" is not displayed)
- Create File ("New File Name" is not displayed)
- Create Directory ("New Directory Name" is not displayed)

**Comment by jordanCain** [comment]
This is not a regression due to the migration away from liberty, however this is still a valid bug.

**Comment by jordanCain** [comment]
fix in https://github.com/zowe/explorer-uss/pull/34

**Comment by jordanCain** [comment]
Verified this is no longer a problem from build 444
