### ISSUE TITLE
"Save As" button in full screen mode view (Direct URL for a known path) fails

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/explorer-uss#31]
With Zowe build 414:

https://tvt7050.svl.ibm.com:7554/ui/v1/explorer-uss/#/editor?file=/u/ibmuser/testDir/testfile3.txt

When I modify a file and click on "Save As" Button, in "Save File AS" page, in the filed showing the directory name, instead of having the current directory name, there is "/u/loading…". It is not modifiable. I had been waiting for 3 minutes to see if it loads the directory name or not, it didn't work.

**Comment by jordanCain** [comment]
Disregard the last message I'm now able to reproduce by forcing a page reload

**Comment by NayerNajafi** [comment]
Yes, with Chrome, it loads successfully, but with Firefox it is in loading state.

**Comment by jordanCain** [comment]
Fix in https://github.com/zowe/explorer-uss/pull/33

**Comment by jordanCain** [comment]
Verified this is no longer a problem from build 444
